### ISSUE TITLE
Unable to parse tagged template

### ISSUE THREAD

**Issue by migonzalvar** [wilsonzlin/ecma-rs#10]
I get an error trying to minify a tagged template literal.

```js
// tagged_template.js 
const noop = (raw, ...keys) => keys.length === 0 ? raw[0] : String.raw({ raw }, ...keys)
template = noop`a`
console.log(template)
```

```console
$ ./minify-js --mode global tagged_template.js 
thread 'main' panicked at 'minify: ExpectedSyntax("expression operator") [token=Some(LiteralTemplatePartStringEnd)] around ```a```', cli/src/main.rs:38:52
```

I get the same error with other examples at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates.

**Comment by wilsonzlin** [comment]
Thanks for raising, I've implemented support in https://github.com/wilsonzlin/parse-js/commit/aff0e9b20dd5b89ffdd5a455a8b342323e6d8c78.
