### ISSUE TITLE
Fails to parse wasm-bindgen output

### ISSUE THREAD

**Issue by Carlrs** [wilsonzlin/ecma-rs#3]
Example wasm-bindgen output js file [here](https://pastebin.com/Ae9DE2Y5), parser fails in async function init(input), with the following error:

Syntax(RequiredTokenNotFound(ParenthesisOpen) [position=42719 token=Some(Dot)] around ```xample-2406131f4c7c9f81_bg.wasm', import.meta.url);
    }
    const imports = ge```)'

**Comment by wilsonzlin** [comment]
Thanks for raising this issue and providing a PR, I've added support for parsing `import.meta` in version 0.3.2, let me know if it works. I've gone with a different approach to the PR as `meta` is a property, so there can be whitespace between the three tokens `import`, `.`, and `meta`.
