### ISSUE TITLE
Failed to parse the "import" function

### ISSUE THREAD

**Issue by sgkoishi** [wilsonzlin/ecma-rs#8]
```javascript
import('file.js');
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

`import` can be used with a function syntax instead of a keyword. For both Global and Module, it results in the parse error result:
```
Error: RequiredTokenNotFound(ParenthesisClose) [token=Some(Semicolon)] around ```;```
```

**Comment by wilsonzlin** [comment]
Thanks for raising, it was being parsed as an expression but (due to a typo) was trying to parse two closing parentheses (`))`) instead of just one.
